import Footer from "@/app/components/footer/footer";
import DesktopHeader from "@/app/components/header/desktopHeader";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "دیجی کالا | لیست محصولات",
  description: "Generated by create next app",
};

export default function ProductListLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <DesktopHeader />
      {children}
      <Footer />
    </>
  );
}
