import Footer from "@/app/components/footer/footer";
import { Metadata } from "next";
import ProductListHeader from "./components/productListHeader";

export const metadata: Metadata = {
  title: "دیجی کالا | لیست محصولات",
  description: "Generated by create next app",
};

export default function ProductListLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ProductListHeader />
      {children}
      <Footer />
    </>
  );
}
